# Generated by Django 3.0 on 2020-02-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_goods',
            name='itemdesc',
            field=models.CharField(max_length=255),
        ),
    ]
